apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-platform.fullname" . }}-runtime
  labels:
    {{- include "api-platform.labelsPWA" . | nindent 4 }}
data:
  runtime.json: |
    {{- if .Values.pwa.runtime }}
    {{ toJson .Values.pwa.runtime | nindent 4 }}
    {{- else }}
    {}
    {{- end }}

